version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-clinic_development}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-clinic_development}
      RAILS_ENV: development
    volumes:
      - ./bootstrap:/bootstrap:ro
      - rails-cache:/usr/local/bundle
      - ./app-persist:/app
    ports:
      - "3000:3000"
    command: ["bash", "/entrypoint.sh"]
volumes:
  db-data:
  rails-cache:
